### ISSUE TITLE
first choice factory metrics

### ISSUE THREAD

**Issue by Bla1** [ZeroK-RTS/Zero-K-Infrastructure#2341] opened 2018-06-21 08:27 UTC
I believe we could establish better metrics for players' first pick factories. We should record and publicly display each factory's global pick rate, win rate, and lose rate. On the replay site, I think it would also be cool to show the factory each player picked.

This could give us better balance metrics, in addition to being cool.

**Comment by sprunk** [comment] 2018-06-21 10:34
Duplicate of #2279

**Closed by sprunk** 2018-06-21 10:34 UTC
