### ISSUE TITLE
Server sent bad json

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2490] opened 2019-02-18 11:20 UTC
```[f=-000001] [liblobby] Error: Failed to parse JSON: {"AccountID":4Welcome {"Engine":"104.0.1-287-gf7b0fcc","Game":"Zero-K v1.7.2.1","UserCount":45,"Version":"1.4.9.194","Factions":[{"Name":"Dynasty of Man","Shortcut":"Dynasty","Color":"#FFBF00"},{"Name":"Empire","Shortcut":"Empire","Color":"#6010FF"},{"Name":"Federation","Shortcut":"Federation","Color":"#55BB55"}],"UserCountLimited":false}```
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/2875327/infolog.txt)

**Comment by DeinFreund** [comment] 2019-02-18 11:34
#2287 ?

**Comment by GoogleFrog** [comment] 2019-02-18 12:20
Could be. I did lose connection and rejoin.

**Comment by sprunk** [comment] 2024-09-22 16:04
Duplicate of #2648

**Closed by sprunk** 2024-09-22 16:04 UTC
