### ISSUE TITLE
Make MM map picker implement the gamblers fallacy

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2554] opened 2019-04-11 02:52 UTC
The matchmaker map picker is too random for the human concept of randomness. Maps that a player has not played in a while should be more likely to come up for them. Short strings of maps should have fewer repeats than would be expected under pure randomness. Every player should never play the same map twice in a row (this is the easiest and most important part of this ticket).

**Comment by dvr333** [comment] 2019-04-11 03:14
Related to #2555

**Comment by Licho1** [comment] 2019-04-11 07:59
They might still crop out in a slightly different version

**Comment by sprunk** [comment] 2019-04-11 11:37
Duplicate of #2215

**Closed by sprunk** 2019-04-11 11:37 UTC
