### ISSUE TITLE
Cannot find errors

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2115] opened 2018-03-25 01:58 UTC
I don't see anything broken in these reports.

https://github.com/ZeroK-RTS/CrashReports/issues/3901
https://github.com/ZeroK-RTS/CrashReports/issues/3903
https://github.com/ZeroK-RTS/CrashReports/issues/3910
https://github.com/ZeroK-RTS/CrashReports/issues/3911

**Comment by sprunk** [comment] 2018-03-25 02:06
Duplicate of #2051

**Closed by sprunk** 2018-03-25 02:06 UTC
