### ISSUE TITLE
ZKL doesn't show in wich room certain player is

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K-Infrastructure#455] opened 2015-02-05 14:30 UTC
The toolbar over the player name doesn't show it anymore. It only shows whether that the player is playing or not.
While that it also doesn't how long the battle has been running (wich also applies to room browser as well).

**Comment by DeinFreund** [comment] 2015-02-05 17:41
Because of this it is also no longer possible to use "Join same battle".

**Comment by Licho1** [comment] 2015-02-05 20:58
ITs caused by some crash in icon manager, should be fixed in master we will see tommorow after relase

**Closed by Licho1** 2015-02-05 20:58 UTC

**Comment by Orfelius** [comment] 2015-02-06 09:12
+1
