### ISSUE TITLE
Proper awarding for squadded teammates

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#2271] opened 2018-05-08 10:20 UTC
Maybe every member of the squad should get the awards, instead of the squad creator?

https://steamcommunity.com/app/334920/discussions/1/1696046342871086755/

**Comment by sprunk** [comment] 2018-05-08 10:49
Belongs to ingame, duplicate of https://github.com/ZeroK-RTS/Zero-K/issues/1849.

**Closed by sprunk** 2018-05-08 10:49 UTC

**Comment by DeinFreund** [comment] 2018-05-08 11:10
I'm unsure if this doesn't also need support from server. I've had db errors previously when trying to award the same award to multiple players.

**Comment by sprunk** [comment] 2018-05-08 11:15
We will learn whether that is truly the case if something gets implemented ingame and then possibly the ticket could be reopened but I'm fairly sure it won't be required.
