### ISSUE TITLE
SpringFeatures missing

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#873] opened 2015-11-10 10:26 UTC
I joined a room with this map as the set room: http://zero-k.info/Maps/DetailName?name=Xanthe%20Terra%20%28Remake%29%20-%20v02

When I launched the game Spring exits with message "Archive "spring features v1.6" not found".

**Comment by Licho1** [comment] 2015-11-11 09:53
This item has no listed internal dependencies.
Investigate why (unitsync, autoregistrator, whatever uploaded metadata)

**Comment by knorker** [comment] 2015-11-11 20:58
duplicate of #682 ?

**Comment by Licho1** [comment] 2015-11-12 07:35
To fix this and similar bugs, remove maps from resource list, when they re-register. If they re-register, because http://api.springfiles.com/files/maps/ does not contain spring features so it might be unable to unitsync them at all due to missing deps.

**Comment by Anarchid** [comment] 2015-11-12 13:21
Spring features is not a map, so shouldn't be contained in SF maps query.
Spring features of all versions is available via rapid.
The real oppression is AutoRegistrator being unable to parse map dependencies (while it knows how to parse `mod` dependencies).
I'm completely sure that is the case for all related bugs because i was able to remedy this for specific maps by injecting dependencies right into the database.

**Comment by Licho1** [comment] 2015-11-12 13:29
Dunno, I know that we upgraded unitsync recently (from 0.82.3). Not sure if past version had it (map deps) but the new one is even refusing to unitsync if dependency is missing (wont give minimap etc). It has to be rewritten to first find dependencies, then dl and then try to extract metadata from map.

**Comment by Anarchid** [comment] 2015-11-12 13:30
Past version also didn't parse deps, the code is missing. I remember us talking about this some time in the past, but that seems to have been in log so most of the data was lost. The discussion involved actual lines of code being mentioned e.g. where to insert the parsing logic, etc.

**Comment by abma** [comment] 2015-11-16 10:44
spring-features is at rapid:

http://repos.springrts.com/repos.gz

**Closed** 2016-02-10 13:56 UTC
