### ISSUE TITLE
Make HTTPS default on website

### ISSUE THREAD

**Issue by Oflameo** [ZeroK-RTS/Zero-K-Infrastructure#2636] opened 2019-10-16 15:18 UTC
Make HTTP Default on website to make it more likely that someone going to the Wiki is logged in when editing. It is not possible to login to the wiki over HTTP, and must be done over HTTPS. That can be changed but it would be better to protect the accounts by making HTTPS default across the site instead.

**Comment by DeinFreund** [comment] 2019-10-16 15:26
Duplicate of https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1795

**Closed by DeinFreund** 2019-10-16 15:26 UTC
