### ISSUE TITLE
MM Map picking should avoid repeats

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K-Infrastructure#2555] opened 2019-04-11 02:53 UTC
When choosing what map to pick, the matchmaker should, as much as possible, avoid picking a map that any player has played last, possibly also taking into account second or third last, but the idea being to avoid repeats. 

Ideally this would work in a cyclic way, where the MM cycles through every map before reshuffling the list and repeating (like how modern tetris chooses blocks) but that's probably too much for a system where separate players will have played a different set of maps prior to the current MM game.

An approach that comes to mind is to store the last to nth last maps played, then try to find a map from the set that excludes maps from last played to nth last played; if that set is empty, try again excluding last to n-1th last, and so on until a non-empty set comes up.

**Comment by sprunk** [comment] 2019-04-11 11:37
Duplicate of #2554

**Closed by sprunk** 2019-04-11 11:37 UTC
