### ISSUE TITLE
Custom comms are not appearing in game

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K-Infrastructure#2622] opened 2019-09-15 22:38 UTC
Current game and last game ( http://zero-k.info/Battles/Detail/771312 )  have not had custom comms for some reason.

**Comment by Arch-Shaman** [comment] 2019-09-15 22:52
http://zero-k.info/Battles/Detail/771317 another game which had no custom comms

**Comment by Arch-Shaman** [comment] 2019-09-15 23:12
Suddenly it's working okay. Not sure if issues are resolved or if it is a sporadic outage or what.

**Comment by sprunk** [comment] 2019-09-16 14:09
My blind guess would be that either the people involved all had many complex commanders which exceeded available space (modoption string length), or somebody put weird characters like [horseshit](https://en.wiktionary.org/wiki/%F0%9F%9D%96) into a name which the game wouldn't parse.

**Comment by Anarchid** [comment] 2019-09-17 11:41
I've checked commander names for http://zero-k.info/Battles/Detail/771317 and while some of them are offensive and possibly should warrant an admonition, none contain non-ascii characters.

**Comment by sprunk** [comment] 2019-09-19 11:09
Unparsable doesn't have to mean non-ascii, apparently it was a backslash. Duplicate of #2626

**Closed by sprunk** 2019-09-19 11:09 UTC
