### ISSUE TITLE
(zKlobby/server?) offline chat history is doubled

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#775] opened 2015-09-02 16:56 UTC
1) Log into lobby, #zk channel

2) The offline chat history is there twice

**Comment by Skasi** [comment] 2015-10-13 07:46
Perhaps worth noting: this is only true for #zk, **no other channel** has doubled history.

**Comment by Licho1** [comment] 2015-11-04 16:59
does not seem to be happening anymore

**Comment by db81** [comment] 2015-11-04 23:55
Still happens to me in #zk and #zkadmin.

**Comment by Licho1** [comment] 2015-11-05 09:02
How do I replicate this?

**Comment by Skasi** [comment] 2015-11-05 12:32
db81 are/were you !subscribed to the channel? Maybe this could be an old leftover?

**Comment by db81** [comment] 2015-11-06 00:42
I found that the reason it happens for me is that swl sends ```JoinChannel {"ChannelName":"zk","Password":null}
``` on login because #zk is set to autojoin locally and then zkls makes me join #zk server-side which results in two sets of ```JoinChannelResponse {"ChannelName":"zk", ... } *insert backlog*``` being sent.

So it's trivial to work around this, but I'd much rather see it fixed in zkls for consistency. Looking at #514 and #720, I feel it could use more internal consistency in general.

**Comment by Licho1** [comment] 2015-11-06 10:26
im not sure it can be fixed. After you send join it sends data. So if there is a double join there is double data. If you think there is a bug reopen with specifics.
Server responds to join request even if you are in the channel in this case by design (to avoid some issues when client state is mismatched especially with multiple clients connected as same user)

**Comment by KingRaptor** [comment] 2015-11-08 01:56
Is it me or does ZKL refuse to stop autojoining #zk when told to?

(the autojoin field is unchecked, but on next startup it's back again)

**Comment by Licho1** [comment] 2015-11-08 10:35
Zkl does not auto join it. Server does autojoining. It is indeed mandatory for all.

**Comment by Anarchid** [comment] 2015-11-17 11:51
This seems to still be happening a lot.
Would force-joins not pouring down history fix this?
If not, would adding a 'wantHistory' parameter to voluntary joins?
Or any combination thereof?

**Comment by KingRaptor** [comment] 2015-11-17 12:21
My problem with ZKL is that I can tell it not to autojoin #zk, but when I restart client it readds #zk to the autojoin list.
9e632c434ac4d4bb7823cb85b6a8d82805dc70a9 may fix it but I haven't tested yet.

**Comment by db81** [comment] 2015-11-17 12:34
Recently zkwl gave me some of the messages I'd already seen after I lost connection and reconnected a few minutes later. It happened in #zkdev *and* #zk, so unrelated to JoinChannel.

**Comment by Licho1** [comment] 2015-11-17 12:44
This is to be expected. It only tracks last login/logout. In some, like
server restart it can miss to register "logout" and sends data from last
known logout - previous.

2015-11-17 13:34 GMT+01:00 Danny B <notifications@github.com>:

**Comment by db81** [comment] 2016-01-03 14:58
Does this still happen to anyone? All (very few) recent instances of it happening to me can be explained by the server not registering a logout.

**Comment by Skasi** [comment] 2016-01-03 17:38
Still happens to me quite often, perhaps always.

**Comment by KingRaptor** [comment] 2016-01-10 02:27
Skasi: on ZKL? Go to settings -> Automatically Joined Channels and remove the entry "zk" if it exists.
(I recently fixed it so it doesn't put `#zk` back on the autojoin list at next start)

**Comment by Skasi** [comment] 2016-01-12 00:23
Removed it and doubled chat messages seem to be gone. Perhaps force-joining should be removed and only autojoining used instead? Otherwise people might be able to accidentally manually recreate the doubled-history-bug.

**Comment by db81** [comment] 2016-01-12 03:56
Maybe, but I'd like to hear @Licho's reasons for making it mandatory first.

**Closed by db81** 2016-01-12 03:56 UTC

**Comment by Licho1** [comment] 2016-01-12 09:24
Mostly for simplicity so that lobby clients dont have to maintain that list. It's also lobby client independent that way.

**Comment by db81** [comment] 2016-01-12 09:34
Yeah keep it that way. It's not just #zk, but #zkadmin and clan/faction channels too, if we remove autojoin lobbies would have to handle all of it, extra work for no gain.
