### ISSUE TITLE
Chobby/wrapper downloads arbitrary wrong version and launches campaign with it

### ISSUE THREAD

**Issue by Histidine91** [ZeroK-RTS/Zero-K-Infrastructure#2558] opened 2019-04-17 14:45 UTC
User CatLady has a bug where campaign LuaRules crashes because it launches with an old Zero-K version not compatible with current engine: v1.7.3.7. This version is not any of the last three fallback versions specified in mainConfig.lua (those would be v1.7.4.0, v1.7.3.10, and v1.5.2.5).

The incorrect version v1.7.3.7 is loaded from archive `720e2b00243185a8aa83d1e74802fb70.sdp`. This file appears in /packages after user empties the folder and launches Zero-K (reaching Chobby main menu). No file download is reported in wrapper GUI, nor does a file download popup appear in Chobby when launching the game.

I am unable to find any instance of `1.7.3.7` in any .lua, .json, or .txt file in the ZK or Chobby repos.

Multiplayer is unaffected.

Sub-issue of https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2525

**Comment by Anarchid** [comment] 2019-04-17 14:47
Also looks like https://github.com/ZeroK-RTS/Zero-K/issues/3520

**Comment by sprunk** [comment] 2019-04-17 16:40
I looked at https://repos.springrts.com/zk/versions.gz and it looks correct.
```
zk:stable,073cc6ffbc2d48f617aeca0c21bfee35,,Zero-K v1.7.4.1
zk:test,69d3133779836b81d3f72709afa673f0,,Zero-K test-15166-9a9c118
```

**Comment by GoogleFrog** [comment] 2019-04-19 08:06
![image](https://user-images.githubusercontent.com/1318249/56414425-dd2c5a80-62cd-11e9-9b9f-cec5103bd8c1.png)

**Comment by sprunk** [comment] 2019-04-26 12:20
CatLady feedback

>01:08 [CatLady] Histidine GoogleFrog  my campaing issues went away as soon as I purg'ed every remnant of .deb package that was once on itch page (removed by Histi) - miraculously, without removing my installation, configs, or using portable, on next startup, ZK used proper version for engine
01:09 [CatLady] so, if yuo want to get to the root of issue, I suggest dissecting what really the .deb package does, and where it keep it. I am not suggesting that it is only problem for people using .deb - all the three of them :wink: but maybe, something else does same thing somewhere else

**Comment by GoogleFrog** [comment] 2019-04-27 09:28
Someone is still submitting crash reports with 1.7.3.7
- https://github.com/ZeroK-RTS/CrashReports/issues/21644
- https://github.com/ZeroK-RTS/CrashReports/issues/21645
- https://github.com/ZeroK-RTS/CrashReports/issues/21646
- https://github.com/ZeroK-RTS/CrashReports/issues/21647

**Comment by DeinFreund** [comment] 2019-04-27 09:32
That seems like a rather wonky install. If it can't connect to the server
to download files I wouldn't expect it to update correctly.

**Comment by Oflameo** [comment] 2019-04-28 14:37
[rapid.zip](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/3125090/rapid.zip)

Here is the contents of my Rapid folder.

**Comment by DeinFreund** [comment] 2019-04-28 17:53
`zk:stable,720e2b00243185a8aa83d1e74802fb70,,Zero-K v1.7.3.7`

As suspected, rapid wasn't updated. Does Steam really take care of it?

**Comment by DeinFreund** [comment] 2019-04-28 21:19
Turns out there are two versions of `zk:stable` in that rapid folder. One is the one maintained by steam which is correct. There's another, older versions.gz in another folder that is leading to the problem here.

See #2567

**Comment by Oflameo** [comment] 2019-04-29 19:02
What is the work around?

**Comment by Oflameo** [comment] 2019-04-29 21:16
[infolog.2019-04-29.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/3129224/infolog.2019-04-29.txt)
Uploading infolog for troubleshooting.

**Comment by Oflameo** [comment] 2019-04-29 21:19
[infolog_full.2019-04-29.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/3129231/infolog_full.2019-04-29.txt)
 Uploading infolog_full for troubleshooting.

**Comment by DeinFreund** [comment] 2019-04-29 21:23
Oflameo is using standalone. After renaming rapid it never redownloaded. There might be some connection issue or something else stopping wrapper from updating rapid.

**Comment by Oflameo** [comment] 2019-04-29 21:27
```
Zero-K                                         
--2019-04-29 17:25:48--  https://zero-k.info/lobby/Chobby.exe                                        
Resolving zero-k.info (zero-k.info)... 37.59.49.101
Connecting to zero-k.info (zero-k.info)|37.59.49.101|:443... connected.                              
HTTP request sent, awaiting response... 304 Not Modified                                             
File ‘Chobby.exe’ not modified on server. Omitting download.                                         

Chobby.exe Information: 0 : Checking for self-upgrade                                                
Chobby.exe Information: 0 : Querying default engine                                                  
Chobby.exe Information: 0 : Reseting configs and deploying AIs                                       
Chobby.exe Information: 0 : Connecting to steam API                                                  
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.                               
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Chobby.exe Information: 0 : Starting
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.                               
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Chobby.exe Information: 0 : Chobby connected to wrapper                                              
Chobby.exe Information: 0 : Chobbyla >> WrapperOnline {"UserID":"661840140","DefaultServerHost":"zero-k.info","DefaultServerPort":8200,"IsSteamFolder":false}                                              

Chobby.exe Information: 0 : Chobbyla << DiscordUpdatePresence {"state":"In Menu"}                    
Chobby.exe Information: 0 : Chobbyla << DiscordUpdatePresence {"state":"In Menu"}                    
Chobby.exe Information: 0 : Chobbyla >> DiscordOnReady {}                                            

[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.                               
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Chobby.exe Warning: 0 : Error executing xprintidle : ApplicationName='xprintidle', CommandLine='', CurrentDirectory='', Native error= Cannot find the specified file                                       
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.                               
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Chobby.exe Information: 0 : Chobby closed connection                              
```

**Comment by Licho1** [comment] 2019-04-30 07:59
You can mess your copy if you run something from commandline in steam folder.
Something like pr-downloader.
To fix it, delete steam folder and let it be redownloaded.

**Comment by DeinFreund** [comment] 2019-04-30 09:49
He's not even using steam. For some reason the wrapper is not updating his rapid.

**Comment by Licho1** [comment] 2019-04-30 11:31
Why is he not using steam? Is non steam even supported?

**Comment by Anarchid** [comment] 2019-04-30 12:25
Itch is supported. Itch is not steam.

**Comment by Oflameo** [comment] 2019-05-01 20:05
Is there a work around?

**Comment by mvollrath** [comment] 2019-05-01 20:11
I had the same issue on Linux with Itch installer, nuking the entire directory fixed it.  Restored the previous maps path and that worked fine.

**Comment by Licho1** [comment] 2019-05-02 09:25
We would need to remake and redeploy itch installer. 
Should we unfeature it instead?

**Comment by Histidine91** [comment] 2019-05-02 11:17
Which one's the Linux itch installer? The old Debian installer was buggy so I got rid of it, but if the semi-portable archive (installed either on its own or through the itch client) isn't working that's a problem.

**Comment by Oflameo** [comment] 2019-05-03 21:50
Using the portable archive on Itch with the Zero-K_old.sh script works for me.

**Comment by GoogleFrog** [comment] 2019-05-17 02:16
https://github.com/ZeroK-RTS/CrashReports/issues/22020
https://github.com/ZeroK-RTS/CrashReports/issues/22021

**Comment by GoogleFrog** [comment] 2019-07-03 11:26
See https://github.com/ZeroK-RTS/Chobby/issues/698

**Comment by Licho1** [comment] 2022-05-05 13:25
probably caused by now fixed issues in wrapper

**Closed by Licho1** 2022-05-05 13:25 UTC
Labels: bug, distribution
