### ISSUE TITLE
"!poll start" does not start games containing no players

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1740] opened 2017-05-20 13:29 UTC
Instead the user must type "!start". I think polls should automatically pass when there are no players, for simplicity in chobby coding.

**Comment by Licho1** [comment] 2017-05-29 15:39
Its the other way around. 
You should use command without poll like "!start"
if you dont have permission, poll is auto used.

if you send "!poll" it means you specifically request a poll even when it is not needed..
Solution .. do not send !poll if you just want to !start

**Comment by DeinFreund** [comment] 2017-05-29 17:10
This would mean whoever creates a public room needs to manually type "!poll start" whenever he wants to start a game without annoying other players in his room who might not have wanted to play on the current map/setting/etc.

**Comment by sprunk** [comment] 2017-05-29 18:00
I think it's good that `!start` does not make a poll if you're the room owner. In all other games, when the owner says start, it just starts, and everyone else does not even have the ability to make a poll.

**Comment by DeinFreund** [comment] 2017-05-29 18:20
In most other RTS there is either a "ready" mechanic or a countdown on start. You also often need to join a new room after every game to confirm your intention of playing. Keep in mind that COOP and funny/special game modes will remain on public custom hosts.

The removal of auto-spec has already degraded the quality of these games (which is what the majority of zk players plays) by increasing the number of people missing ingame, instant start would only add to these cases. I don't think it's the goal to degrade the quality of public hosts until you either play with friends or join MM?

The dilemma is that you need to unspec to participate in votes, but this simultaneously marks you as ready to play, which you are not when trying to vote for a change in setting. There doesn't seem to be much of an improvement over the original ready/unready status. Alternatively, the player/spectator status could be removed completely in favor of presenting every player with a "Join" option as soon as start is called. This means every player willingly agrees with the current settings instead of a weird vote/force start. Or do we want to force players into games because otherwise there aren't enough of them?

**Comment by GoogleFrog** [comment] 2017-05-30 02:19
The start button should not start the game if you have permissions. This relies on people remembering whether they are the host of the room to determine what the button will do. It makes the UI broken for moderators when the default is to force start any room.

**Comment by Licho1** [comment] 2017-06-01 10:18
Why should random people who enter your game prevent game from starting (by voting no) ?

**Comment by GoogleFrog** [comment] 2017-06-01 10:30
Because it is more important that the host not start the game accidentally when someone else isn't ready.

**Comment by Licho1** [comment] 2017-06-01 11:34
But non ready people wont cause start to abort, its a majority vote.

**Comment by GoogleFrog** [comment] 2017-06-01 13:20
The non-ready players can say "wait, that person is not ready" and it adds a time between pressing start and the game actually starting.

**Comment by sprunk** [comment] 2017-06-01 13:26
Things detectable by other people (no map; afk) used to be handled by auto-spec. Why was it removed?

Last minute change of mind is probably best handled by a short timer, the standard in other room based games.

**Comment by Licho1** [comment] 2017-06-01 13:35
Auto spec was removed for two reasons:
1) you can assume people have content (steam)
2) even if they don't, download is in progress and in-game there is further 90s wait - plenty for them to download map and join.

Lobby should continue downloading content and join game as soon as it is ready.

**Comment by sprunk** [comment] 2017-06-01 13:40
OK about content, what about afk?

**Comment by DeinFreund** [comment] 2017-06-01 13:48
Why should the host be allowed to force people into a game who might just quit or troll because they didn't want to play with the current setting?

**Comment by sprunk** [comment] 2017-06-01 14:20
>Why should the host be allowed to force people into a game (...)

Because that's what the host is for. If people want a game with guaranteed non-shitty settings they should join MM. Or, if we want to design the whole system around the current playerbase of 20 stubborn vets playing in a single clusterfuck room then we shouldn't have removed Springie.

As a side note, if other people vote start in a poll then the people who vote no are still dragged inside. The vote leaves some time to do that but so would a timer.

> (...) who might just quit or troll because they didn't want to play with the current setting? We can't blame people if they didn't actually agree to join the game

Again, playerbase problem. People agree to the settings by staying in a room after settings change. Current people keep AFKing in battlerooms and don't pay attention. If people paid attention then they would notice unwanted settings and either voice their concerns to the host or go to another room. Possibly there could be improvements in the way hosts can signal what they're up to, so that people can tell at a glance that the host offers what they want. For example the host could not change the map to a different featured/silly level (no luring people with a decent setting then switching to shitmap).

>due to the inability to actually change settings to what they want as a spectator you can't expect them to spectate either

The ability exists and is called "talk to host". If it doesn't work then they should go to another room.

>lol but there are no other rooms

Sure, if we keep the design revolving around 1 room culture then no wonder there aren't any other rooms.

**Comment by Licho1** [comment] 2017-12-16 23:58
closing, poll start is by design, use !start if you want to start, poll forces poll

**Closed by Licho1** 2017-12-16 23:58 UTC
