### ISSUE TITLE
Required number of votes miscounted

### ISSUE THREAD

**Issue by db81** [ZeroK-RTS/Zero-K-Infrastructure#1283] opened 2016-10-02 12:55 UTC
Not sure how to reproduce. A poll will ask for more players than are unspecced. Happens with !start and !map at least. Opening a new room fixes it.

Not very useful chat log of it happening: http://pastebin.com/jM87BhVg

Apparently that wasn't the only time:

```
[11:11:07 PM]   <Aquanim>   why are map change polls requiring one more player than
the total number of players active to pass?
[11:31:34 PM]   <zenfur>    it was server player count bug
[11:31:37 PM]       I see that a lot
[11:31:40 PM]       recently
```

**Comment by Licho1** [comment] 2016-10-02 12:58
Soectating admins count as players for the purpose of poll -they have vote reserved in every poll by design.

**Comment by db81** [comment] 2016-10-02 12:59
What.

I thought that was a joke.

**Comment by GoogleFrog** [comment] 2016-10-02 13:08
Spectating admins should not count as players. They could be AFK and no admins actually know that they count as players.

**Comment by Aquanim** [comment] 2016-10-07 13:46
There are votes like !kick where admins having a vote makes sense.

!start vote when a bunch of admins are afk in room, making the game literally unstartable, is not one of those cases.

**Comment by Licho1** [comment] 2016-11-19 13:20
this got fixed by @KingRaptor

**Closed by Licho1** 2016-11-19 13:20 UTC
Labels: bug, springie
