### ISSUE TITLE
Split Start

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#917] opened 2015-12-30 13:40 UTC
Our current autohosts should be used to start multiple game. If players are in a host which is currently running a game they should be able to vote to start a game.
 * This vote only counts the non-ingame players are voters.
 * The intention of the vote is that non-ingame players can start a new game.
If the vote passes then the non-ingame players would enter a game, just as if they had passed a start vote anywhere else. This could be done by splitting the players to a new host and starting the game.

Votes which are not relevant to the game should be supressed in the ingame chat. Ideally ingame and out of game votes would be able to happen simultaneously.

The aim of the suggestion is to create the possibility of two game rooms at once in the current "stack into a running room" culture.

**Comment by db81** [comment] 2015-12-30 14:53
Duplicate of #733?

**Comment by Licho1** [comment] 2016-09-28 12:46
not relevant anymore

**Closed by Licho1** 2016-09-28 12:46 UTC
Labels: enhancement, springie
