### ISSUE TITLE
Website should forward HTTP to HTTPS

### ISSUE THREAD

**Issue by beamer159** [ZeroK-RTS/Zero-K-Infrastructure#2624] opened 2019-09-17 02:45 UTC
When I type "zero-k.info" into my web browser, it brings me to the insecure "http://zero-k.info". Most other websites automatically forward HTTP requests to their HTTPS website. The Zero-K website should do the same.

**Comment by sprunk** [comment] 2019-09-17 10:13
Duplicate of #1795

**Closed by sprunk** 2019-09-17 10:13 UTC
