### ISSUE TITLE
Site throws Error randomly

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1721] opened 2017-04-22 18:49 UTC
From time to time, instead of receiving the site I requested, this is served:
`The custom error module does not recognize this error.`

I have yet to find a pattern behind this, it happens randomly on any part of the zk site. It also doesn't seem to appear in the logs. Is there a way to debug this?

**Comment by Licho1** [comment] 2017-04-23 05:36
It is the "spam" prevention thing. It is expected. 
Code is https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Zero-K.info/AppCode/DosProtector.cs

**Comment by DeinFreund** [comment] 2017-04-23 13:54
Even though you've already relaxed the limits, it keeps happening while I'm just regularly using the site. Are you sure it's working correctly?

**Comment by Licho1** [comment] 2017-04-24 07:44
I think it is, problem is hovering tooltips, these generate extra request, so if you do a thing like sliding 20 names quickly you can exceed it.
Tooltip widget should be modified to be more sensible.

**Comment by DeinFreund** [comment] 2017-04-24 10:03
It also happens when using the site search.

**Comment by KingRaptor** [comment] 2017-08-03 14:08
I think this can be treated as a duplicate of #1778.

**Closed by KingRaptor** 2017-08-03 14:08 UTC
Labels: website
