### ISSUE TITLE
rhodium and neptunium have no bot flag

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#977] opened 2016-03-13 09:14 UTC
when you sort by players in battle list you will see experienced and serious hosts have one player which is the host itself.
Other springies do not have that problem

**Comment by sprunk** [comment] 2016-04-02 09:06
What lobby do you use? Not a problem in ZKL

**Comment by sprunk** [comment] 2016-04-02 09:35
This has two separate parts.

The first is that your lobby shows non-bot host as a player. This is a flobby problem and does not happen in ZKL.

The second is that Springies don't have the bot status granted automatically. This is a duplicate of #767

**Closed by sprunk** 2016-04-02 09:35 UTC
Labels: springie
