### ISSUE TITLE
Manually opened hosts can fail to appear

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#399] opened 2015-01-18 10:47 UTC
Sometimes springies fail to appear when you want to open a new battle. Click "Open a new battle" and nothing happens, you just see a bar at the bottom with "Waiting for room" written on it. This is an intermittent bug as sometimes the hosts start successfully.

This is quite important, at least in the current setup, because new players may try to start a game but think the server is down then leave.

**Comment by abma** [comment] 2015-01-18 15:50
very likely a duplicate of #71

**Comment by Licho1** [comment] 2015-01-18 22:34
There is no error message except that "machine has aborted connection" within springie..
I rewrote low level network code to modern standard to see if it helps/get more data

**Comment by abma** [comment] 2015-01-18 22:35
look into server.log from uberserver and search for  OPENBATTLEFAILED...

**Comment by Licho1** [comment] 2015-01-19 09:59
You are right

**Comment by Licho1** [comment] 2015-01-30 01:18
fixed in extra branch

**Closed by Licho1** 2015-01-30 01:18 UTC
