### ISSUE TITLE
Viewing a forum topic about a mod does not mark it read.

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#2831] opened 2021-08-12 09:35 UTC
It stays bold and blue forever unless you press "mark all read", which works.

**Comment by GoogleFrog** [comment] 2021-08-12 12:24
Yes https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2791

**Comment by sprunk** [comment] 2021-08-12 13:34
Duplicate of #2791

**Closed by sprunk** 2021-08-12 13:34 UTC
