### ISSUE TITLE
Matchmaking - Allow optional matching for larger team sizes

### ISSUE THREAD

**Issue by Jazcash** [ZeroK-RTS/Zero-K-Infrastructure#2305] opened 2018-05-23 13:44 UTC
A flag, e.g. "Allow larger team matches" that will allow a party to be matched on a potentially larger team size if no exact team size matches can be found. For example, if no match can be found instantly for 2v2, then expand the search to match for 3v3, then 4v4 and so on until an instant match is found, or until the search parameters match any teamsize at all above 2v2.

**Comment by sprunk** [comment] 2018-05-23 13:45
Duplicate of #2295

**Closed by sprunk** 2018-05-23 13:45 UTC
