### ISSUE TITLE
Issues arise when players join a battle which is started seconds afterwards

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1813] opened 2017-09-18 03:40 UTC
Players can join battles and have them start immediately. This can cause them to play a game that they did not intend to play and can break the game setup (particularly in FFA). 
 * We can not set players to spectator by default. The expected action for clicking on a battleroom is to play the game, being a spectator by default is terrible UI and will lead to new players missing out.
 * Setting people to spectator by default and then asking if they want to play is also pretty terrible UI.

I think some sort of host solution is required. Perhaps if a new player joins the start is cancelled or suspended. This also sounds quite terrible though.

**Comment by sprunk** [comment] 2017-09-18 10:22
Duplicate of #1754.

**Closed by sprunk** 2017-09-18 10:22 UTC
