### ISSUE TITLE
Start games from running battlerooms

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#733] opened 2015-08-03 13:49 UTC
I think player activity would be improved if spectators in player slots could start games from within the battleroom that they are in. This would fit within the current culture as people tend to idle and spec in the running room while waiting for the next game.

Here it how it would work:
 * Start vote could be called for running battle rooms.
 * The number of votes required only takes into account the unspecced players who are not players in the running game (unspecced players who are in the current game as spectators are counted). Only unspecced non-ingame-players can vote.
 * If the vote passes then:
  * A new springie with the same map and room type is spawned.
  * Unspecced non-ingame-players are moved to a new springie.
  * The game is started.

The UI can be left as is, people would have to manually type !start for now. 

If this suggestion is too hard then do not implement it. There are more important things to do. But if this suggestion is something simple (perhaps it mostly reuses !move and planetwars matchmaking) then I think it would be a worthwhile addition to the current room system and could be a good way to transition out of 1-room culture.

**Comment by sprunk** [comment] 2016-03-07 09:09
Duplicate of #917

**Closed by sprunk** 2016-03-07 09:09 UTC
Labels: enhancement
