### ISSUE TITLE
Site wiki icons broken

### ISSUE THREAD

**Issue by Hawkybird** [ZeroK-RTS/Zero-K-Infrastructure#2835] opened 2021-09-01 16:08 UTC
The unit icons don't seem to work because the zero-k.info site uses https. (E.g.: https://zero-k.info/mediawiki/index.php?title=Bandit)
Chrome seems to be trying to replace the icons located at manual.zero-k.info with https but the site doesn't support that, only http.
`Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure element '<URL>'. This request was automatically upgraded to HTTPS`
http://manual.zero-k.info/unitpics/chickenr.png - works
https://manual.zero-k.info/unitpics/chickenr.png - doesn't work

**Comment by sprunk** [comment] 2021-09-01 16:29
Duplicate of #1795

**Closed by sprunk** 2021-09-01 16:29 UTC
