### ISSUE TITLE
ZK site content hosted on 3rd party (non-https) sites

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K-Infrastructure#1727] opened 2017-04-29 07:37 UTC
Browsers start to show warnings like "this is not secure" when entering login/password on website
Can we already move to https?

we could even use free certificate from let's encrypt ^^

**Comment by Anarchid** [comment] 2017-04-29 08:22
Https has been there for a few months already with a letsencrypt certificate. The only missing bit is redirecting to https as default.

**Comment by let4be** [comment] 2017-04-29 08:22
didn't even notice :| redirect is must have

**Comment by let4be** [comment] 2017-04-30 19:18
https://www.dropbox.com/s/7ujhygb4wzrtzif/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202017-04-30%2022.17.11.png?dl=0

**Comment by Anarchid** [comment] 2017-05-02 08:38
Yeah, there's some mixed content.

**Comment by abma** [comment] 2017-05-27 18:38
thats whats on the startpage:

http://packages.springrts.com/zkmanual/unitpics/corgrav.png
http://licho.eu/alba/Zero-K/glaivereapersized.png
http://licho.eu/alba/Zero-K/showcase_small.png
http://licho.eu/alba/Zero-K/showcase_medium.png
http://licho.eu/alba/Zero-K/showcase_big_1.png
http://licho.eu/alba/Zero-K/showcase_big_2.png


should be fixed soon as google prefers https in results.

**Comment by let4be** [comment] 2017-05-27 19:26
we really need to fix this if we want zk to look serious and be rated in search engines higher...

**Comment by sprunk** [comment] 2017-08-09 10:29
Duplicate of #1795

**Closed by sprunk** 2017-08-09 10:29 UTC
Labels: website
