### ISSUE TITLE
Vote weirdness

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K-Infrastructure#2534] opened 2019-04-04 23:35 UTC
http://zero-k.info/Battles/Detail/704065

In this vote, a game of 17 people required only 5 to pass a kick vote instead of 9. This resulted in Hellasciouss receiving kick abuse from their teammates.

**Comment by DeinFreund** [comment] 2019-04-05 09:07
Only teammates get to vote on in-game kicks.

**Comment by Arch-Shaman** [comment] 2019-04-05 13:44
Main issue right now is that TMNL (snoke, Firepluk, etc) is abusing the system repeatedly in order to remove people from the all welcome room (allegedly). [See: http://zero-k.info/Forum/Thread/28122 ]
There's also the related issue of some users calling random kick votes for no reason. It may be necessary to reinstate the "Voting Rights Removal" punishment or total removal of kick from **automated** hosts during (and possibly after) games.

**Comment by DeinFreund** [comment] 2019-04-05 13:47
Yes, we're currently discussing this within the admin team, but as for an actual bug. Is there a case where the vote count required was less than 1/2 of the people eligible to vote? That's the non-afk teammates if in-game and the non-afk players if in lobby.

**Comment by sprunk** [comment] 2019-05-08 18:55
Duplicate of #2072 (the kick requirement part) and #2562 (the vote rights removal punishment part)

**Closed by sprunk** 2019-05-08 18:55 UTC
