### ISSUE TITLE
Steam-related lobby crash

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#957] opened 2016-03-04 21:17 UTC
- seems intermittent
- seems to affect many users 
- happens for a week or so?

```
[7:02:42 PM]	<snoke>	what about random lobby crashes, they are a known bug yet since last update? are there fixes or something yet?
[7:16:29 PM]	<ikinz>	I don't think anyone knows
[7:16:39 PM]		pastebined logs would help
[7:19:21 PM]	<snoke>	heard about that some times already, happens to me since yesterday some times
[7:20:02 PM]		will take a look at locks next time it happens
[7:20:52 PM]		*logs
[7:23:36 PM]		04.03.2016 18:17:33: System.AccessViolationException: 
[7:23:36 PM]		   bei Steamworks.NativeMethods.SteamAPI_InitSafe()
[7:23:36 PM]		   bei Steamworks.SteamAPI.Init()
[7:23:36 PM]		   bei ZeroKLobby.Steam.SteamClientHelper.TimerOnElapsed(Object sender)
```

**Comment by Sortale** [comment] 2016-03-04 21:59
Random Zero-k Lobby crashed

error log does not seem to belong to crash

http://zero-k.info/Forum/Thread/21008

**Comment by Licho1** [comment] 2016-03-06 15:41
Need a proper repro steps. Neither of those logs contain crash ..  - which should be marked with FATAL

**Comment by Sortale** [comment] 2016-03-06 22:10
the problem is it's impossible to get a crash log or intentionally reproduce.

the program just crash randomly and produce no crash log.

is there anything that I can do to get more info for you?

**Comment by Licho1** [comment] 2016-03-07 07:55
yes try running a) without steam running
b) with steam running all the time without closing/starting steam

**Comment by Sortale** [comment] 2016-03-08 09:37
ok I think you are right

preliminary report:

-2 session without steam running: 2 hr then 4 hr both have no crash
- 1 session with steam running without closing steam: crashed in 30-45 min

of course I'll repeat the test tomorrow, but I think you got it.

**Comment by Sortale** [comment] 2016-03-09 02:01
repeat test show the same result.
- session with team running crashed in 30-45 min
- non steam session still running 1-2 hr

**Comment by Licho1** [comment] 2016-09-28 12:44
ZKL discontinued, chobby is the savior.

**Closed by Licho1** 2016-09-28 12:44 UTC
Labels: bug, lobby
