### ISSUE TITLE
Wrapper support for manual crash report

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2065] opened 2018-02-28 11:54 UTC
I want a crash report button in chobby. The user would enter a title and some body text and press send. Then this would happen:
- Chobby asks user "Are you sure? Chobby will close to send the report with infolog that may contain chat.".
- Chobby sends this title and text to the wrapper with a function.
- Wrapper closes Spring.
- Wrapper uses infolog_full and the title and body to make a normal crash report.

**Comment by sprunk** [comment] 2018-02-28 12:39
Duplicate of #2057

**Closed by sprunk** 2018-02-28 12:39 UTC
