### ISSUE TITLE
Wrapper reports failure for map-type mod download

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2757] opened 2020-11-05 02:25 UTC
Host a custom room with game `Unit Level Ups v5`. This appears to have been uploaded to the ZK site via the map/mod upload box, however I cannot find it on the site. Since it is a game, chobby first tries to download it with RAPID. When this fails, chobby tries to download it with MAP, as I was told that this is how to get games that were uploaded to the ZK site. When chobby does this, `wrapperFunctions.DownloadFinished` responds like this:

```
[f=-000001] DownloadFinished, Unit Level Ups v5, RAPID, false, false
[f=-000001] DownloadFinished, Unit Level Ups v5, MAP, false, false
```

This causes players to need to rejoin the room after joining it, as otherwise the lobby doesn't know that the download was a success.

**Comment by Licho1** [comment] 2020-11-05 11:40
Root cause is probably not having the mod marked as mod internally in ZK site, this should be fixed - possible when we upload it we can detect if its a map or mod and categorize properly.

**Comment by GoogleFrog** [comment] 2020-11-08 10:37
Also mods cannot be found.

![image](https://user-images.githubusercontent.com/1318249/98462761-a1881700-220a-11eb-98c8-3b7e9c9d2f09.png)

**Comment by maackey** [comment] 2020-11-09 23:56
// filter only maps
            ret = db.Resources.Where(x => x.TypeID == ResourceType.Map);

Maps filter explicitly only includes resources of type Map on this page. 

Are mods exclusively going to be map-mods? If not I'd like to perhaps create a different page/interface for them -- Maps / Replays / Mods.

**Comment by Licho1** [comment] 2020-11-13 10:15
Ok first - for downloader it should just download it using game/mod mode.
The second  part - what do we show on website is tougher.
There are tens of thousands "mods" stored there, every single test build of ZK and other RAPID games. 

We should filter those that depend on "rapid://zk:stable" this will show actual ZK mods.
I agree we should hae entire new section with mods for this.

**Closed** 2020-11-13 12:00 UTC
