### ISSUE TITLE
Bad json sent

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2287] opened 2018-05-15 15:49 UTC
[f=0000030] [liblobby] Error: Failed to parse JSON: {"Header":{"BattleID":3466,"Engine":"104.0.1-287-gf7b0fcc","Founder":"Musashi_Tenrai","Game":"Zero-K v1.6.5.1","IsMatchMaker":false,"IsRunning":false,"Map":"Gecko Isle 1.1","MaxPlayers":10,"Mode":6,"Password":"?","PlayerCount":1,Welcome {"Engine":"104.0.1-287-gf7b0fcc","Game":"Zero-K v1.6.5.1","UserCount":295,"Version":"1.4.9.180","Factions":[{"Name":"Dynasty of Man","Shortcut":"Dynasty","Color":"#FFBF00"},{"Name":"Empire","Shortcut":"Empire","Color":"#6010FF"},{"Name":"Federation","Shortcut":"Federation","Color":"#55BB55"}],"UserCountLimited":false}

https://github.com/ZeroK-RTS/CrashReports/issues/7538

**Comment by DeinFreund** [comment] 2018-05-15 15:53
These are two messages interleaved. Maybe this is caused by the player rejoining the server and getting another welcome message?

**Comment by sprunk** [comment] 2024-09-22 16:04
Duplicate of #2648

**Closed by sprunk** 2024-09-22 16:04 UTC
Labels: lobbyserver
