### ISSUE TITLE
Experienced host doesn't spectate unexperienced players on start

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1041] opened 2016-05-14 06:10 UTC
> [08:07:50]	Juandex	let me play
> [08:07:53]	SnuggleBass	you're experience gated
> [08:07:55]	Juandex	I dont care
> [08:07:59]	Juandex	im experiencied
> [08:08:00]	Juandex	stfu

how could one start a game in such situations?

**Comment by sprunk** [comment] 2016-05-14 12:15
duplicate of #979

**Closed by sprunk** 2016-05-14 12:15 UTC
