### ISSUE TITLE
[bug] when spectator desyncs game does not count

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#1042] opened 2016-05-14 12:12 UTC
game can count when spectator desyncs. It does not affect players or?

**Comment by sprunk** [comment] 2016-05-14 12:19
duplicate of #818

**Closed by sprunk** 2016-05-14 12:19 UTC

**Comment by CrazyEddieTK** [comment] 2016-05-14 13:00
It's not a duplicate. This issue can be solved without solving the larger issue of keeping all desynced and exited games.

**Comment by Skasi** [comment] 2016-05-14 13:07
> It's not a duplicate.

Yes it is. "If only specs desync then still give elo to all players" was already requested in #816. I dunno why lower number issues are closed over higher numbered ones.

> This issue can be solved without solving the larger issue of keeping all desynced and exited games.

Are you sure? Maybe technically the other issues are not "larger".

**Comment by db81** [comment] 2016-05-14 13:07
Isn't it technically impossible to tell for sure who desynced and who didn't? I wouldn't be surprised if you can't tell whether it was a spec or not either.

**Comment by sprunk** [comment] 2016-05-14 13:25
>This issue can be solved without solving the larger issue of keeping all desynced and exited games.

patches welcome
